language: go

sudo: false

services:
  - redis-server
  - memcached

before_install:
  - go get github.com/mattn/goveralls

before_script:
  - go get ./...
  - go vet ./...

go:
  - "1.10"
  - "1.11.x"
  - tip

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
